# Generated by Django 3.0.8 on 2020-07-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=264)),
                ('RollNo', models.IntegerField()),
                ('Marks', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=264)),
                ('Subject', models.CharField(max_length=64)),
                ('Salary', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
