# Generated by Django 3.0.8 on 2020-07-24 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelInheritence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('contactinfo1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ModelInheritence.ContactInfo1')),
                ('RollNo', models.IntegerField()),
                ('Marks', models.IntegerField()),
            ],
            bases=('ModelInheritence.contactinfo1',),
        ),
        migrations.CreateModel(
            name='Teacher1',
            fields=[
                ('contactinfo1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ModelInheritence.ContactInfo1')),
                ('Subject', models.CharField(max_length=64)),
                ('Salary', models.FloatField()),
            ],
            bases=('ModelInheritence.contactinfo1',),
        ),
    ]
