# Generated by Django 3.0.8 on 2020-07-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelInheritence', '0002_contactinfo1_student1_teacher1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent1',
            fields=[
                ('Name', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Parent2',
            fields=[
                ('RollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Child1',
            fields=[
                ('parent2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ModelInheritence.Parent2')),
                ('parent1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ModelInheritence.Parent1')),
                ('CodeName', models.CharField(max_length=64)),
                ('Salary', models.FloatField()),
            ],
            bases=('ModelInheritence.parent1', 'ModelInheritence.parent2'),
        ),
    ]
