# Generated by Django 3.0.8 on 2020-07-24 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelInheritence', '0003_child1_parent1_parent2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('Name', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ModelInheritence.Parent')),
                ('RollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Marks', models.IntegerField()),
            ],
            bases=('ModelInheritence.parent',),
        ),
        migrations.CreateModel(
            name='SubChild',
            fields=[
                ('child_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ModelInheritence.Child')),
                ('CodeName', models.CharField(max_length=64)),
                ('Salary', models.FloatField()),
            ],
            bases=('ModelInheritence.child',),
        ),
    ]
